# Generated by Django 6.0.3 on 2026-03-18 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='numero',
            field=models.BigIntegerField(null=True),
        ),
    ]
