# Generated by Django 6.0.3 on 2026-03-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_alter_bankaccount_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='balance',
            field=models.BigIntegerField(default=0),
        ),
    ]
