# Generated by Django 6.0.3 on 2026-03-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0004_banktransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='balance_after',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
