# Generated by Django 5.2.12 on 2026-04-03 12:58

import apps.bankapp.models.account
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bankapp", "0005_banktransaction_balance_after_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="first_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="identity_file",
            field=models.FileField(
                upload_to=apps.bankapp.models.account.identity_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="last_name",
            field=models.CharField(max_length=100),
        ),
    ]
