# Generated by Django 6.0.3 on 2026-03-19 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_baseusersession'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='baseuser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='baseuser',
            name='salt',
            field=models.CharField(default='salt', max_length=50),
            preserve_default=False,
        ),
    ]
