# Generated by Django 6.0.3 on 2026-03-20 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_baseuser_managers_baseuser_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
