# Generated by Django 5.2.12 on 2026-04-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_baseuser_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseuser",
            name="two_factor_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
